spring.main.allow-circular-references: true
server:
  port: 80
  servlet:
    context-path: /Shopme

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    password: 73524Idea#    #hikari:      #minimum-idle: 1
      #maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 182557182495-4ojqb7gpdf0cee6i97md5b3tns5sbc1e.apps.googleusercontent.com
            client-secret: zpJMafs7JAf4fNVLZirNcRnO
            scope:
            - email
            - profile
          facebook:
            client-id: 522415793398286
            client-secret: 664b540e1aa5426ca77dbe06dd0535fe
            scope:
            - email
            - public_profile